Delete branches that correspond to accepted stories [#176488902]
Co-authored-by: Charlie Nazario <cnazario@vmware.com>

diff --git a/adapters/fixtures/git b/adapters/fixtures/git
--- a/adapters/fixtures/git
+++ b/adapters/fixtures/git
@@ -5,3 +5,13 @@ args=$*
 if [ "${args}" = "rev-parse --abbrev-ref HEAD" ]; then
     echo "current-branch-123456789"
 fi
+
+if [ "${args}" = "--no-pager branch --format %(refname:short)" ]; then
+    echo "main"
+    echo "some-branch-#123"
+fi
+
+if [ "${args}" = "branch -D some-nonexistent-branch" ]; then
+    >&2 echo "error: branch 'some-nonexistent-branch' not found."
+    exit 1
+fi
